# Generated by Django 4.0.4 on 2022-07-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefone', models.CharField(max_length=10)),
                ('departamento', models.CharField(choices=[('Vendas', 'Vendas'), ('Administracao', 'Administracao'), ('Recursos Humanos', 'Recursos Humanos'), ('Diretoria', 'Diretoria')], max_length=17)),
            ],
        ),
    ]
